// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DynamicCRUD.Metadata;
using System;
using System.Collections.Generic;

namespace WebApplication1.Entities;

public partial class BusinessObjectRelation
{
    public Guid Id { get; set; }

    public string RelationName { get; set; }

    public bool IsBaseObjectRelation { get; set; }

    public Guid? ManyToManyObjectId { get; set; }

    public Guid FromObjectId { get; set; }

    public Guid ToObjectId { get; set; }

    public RelationEnd FromEnd { get; set; }

    public RelationEnd ToEnd { get; set; }

    public string FromRelationName { get; set; }

    public string ToRelationName { get; set; }

    public int? DeleteBehavior { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ForeignKey> ForeignKeys { get; } = new List<ForeignKey>();

    public virtual BusinessObject FromObject { get; set; }

    public virtual BusinessObject ManyToManyObject { get; set; }

    public virtual BusinessObject ToObject { get; set; }
}