// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Entities;

public partial class BusinessObject
{
    public Guid Id { get; set; }

    public bool IsDeletedByUser { get; set; }

    public Guid? BaseObjectId { get; set; }

    public Guid? NamePropertyId { get; set; }

    public bool IsHierarchicalType { get; set; }

    public string QuickSearchAbbreviation { get; set; }

    public string Database { get; set; }

    public Guid? BusinessObjectGroupId { get; set; }

    public Guid BusinessModuleId { get; set; }

    public bool IsManyToManyConnectingObject { get; set; }

    public bool IsImported { get; set; }

    public bool IsCompiled { get; set; }

    public bool IsDeleted { get; set; }

    public string DisplayName { get; set; }

    public string PhysicalName { get; set; }

    public virtual BusinessObject BaseObject { get; set; }

    public virtual BusinessModule BusinessModule { get; set; }

    public virtual ICollection<BusinessProperty> BusinessProperty { get; } = new List<BusinessProperty>();

    public virtual ICollection<BusinessObject> InverseBaseObject { get; } = new List<BusinessObject>();

    public virtual BusinessProperty NameProperty { get; set; }
}