// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Entities;

public partial class BusinessProperty
{
    public Guid Id { get; set; }

    public Guid BusinessObjectId { get; set; }

    public Guid? EnumerationTypeId { get; set; }

    public bool IsDisabled { get; set; }

    public int OrderIndex { get; set; }

    public string MinValue { get; set; }

    public string MaxValue { get; set; }

    public string OriginalImportColumnType { get; set; }

    public string DefaultValue { get; set; }

    public bool IsPrimaryKey { get; set; }

    public bool IsForeignKey { get; set; }

    public Guid? MappingPropertyId { get; set; }

    public Guid? ComputeExpressionId { get; set; }

    public bool IsServiceProperty { get; set; }

    public bool IsDeleted { get; set; }

    public string DisplayName { get; set; }

    public string PhysicalName { get; set; }

    public virtual BusinessObject BusinessObject { get; set; }

    public virtual ICollection<BusinessObjectExpression> BusinessObjectExpressions { get; } = new List<BusinessObjectExpression>();

    public virtual ICollection<BusinessObject> BusinessObjects { get; } = new List<BusinessObject>();

    public virtual BusinessPropertyType BusinessPropertyType { get; set; }

    public virtual BusinessObjectExpression ComputeExpression { get; set; }

    public virtual ICollection<ForeignKey> ForeignKeyForeignKeyProperties { get; } = new List<ForeignKey>();

    public virtual ICollection<ForeignKey> ForeignKeyPrimaryKeyProperties { get; } = new List<ForeignKey>();
}