// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Entities;

public partial class BusinessObjectExpression
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public bool? ApplyToAllPages { get; set; }

    public bool IsShared { get; set; }

    public int Type { get; set; }

    public Guid BusinessObjectId { get; set; }

    public string ErrorMessage { get; set; }

    public bool IsValidatingProperty { get; set; }

    public Guid? TargetPropertyId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessObject BusinessObject { get; set; }

    public virtual ICollection<BusinessProperty> BusinessProperties { get; } = new List<BusinessProperty>();

    public virtual BusinessProperty TargetProperty { get; set; }
}