// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Entities;

public partial class ForeignKey
{
    public Guid Id { get; set; }

    public Guid BusinessObjectRelationId { get; set; }

    public Guid PrimaryKeyPropertyId { get; set; }

    public Guid ForeignKeyPropertyId { get; set; }

    public string ForeignKeyName { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BusinessObjectRelation BusinessObjectRelation { get; set; }

    public virtual BusinessProperty ForeignKeyProperty { get; set; }

    public virtual BusinessProperty PrimaryKeyProperty { get; set; }
}