// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class BusinessModule
    {
        public BusinessModule()
        {
            BusinessObjects = new HashSet<BusinessObject>();
            Permissions = new HashSet<Permission>();
        }

        public Guid Id { get; set; }
        public Guid? DatabaseInfoId { get; set; }
        public bool IsDeleted { get; set; }
        public string DisplayName { get; set; }
        public string PhysicalName { get; set; }

        public virtual DatabaseInfo DatabaseInfo { get; set; }
        public virtual ICollection<BusinessObject> BusinessObjects { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}