// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class BusinessPropertyType
    {
        public Guid Id { get; set; }
        public int DataType { get; set; }
        public int? NumericPrecision { get; set; }
        public int? NumericScale { get; set; }
        public int? MinCharacterLength { get; set; }
        public long? MaxCharacterLength { get; set; }
        public bool IsRequired { get; set; }
        public bool IsSigned { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BusinessProperty IdNavigation { get; set; }
    }
}