// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class BusinessObject
    {
        public BusinessObject()
        {
            BusinessObjectExpressions = new HashSet<BusinessObjectExpression>();
            BusinessObjectRelationFromObjects = new HashSet<BusinessObjectRelation>();
            BusinessObjectRelationManyToManyObjects = new HashSet<BusinessObjectRelation>();
            BusinessObjectRelationToObjects = new HashSet<BusinessObjectRelation>();
            BusinessProperties = new HashSet<BusinessProperty>();
            ExpressionNodeCountObjects = new HashSet<ExpressionNode>();
            ExpressionNodeFroms = new HashSet<ExpressionNode>();
            ExpressionNodeTargetObjects = new HashSet<ExpressionNode>();
            InverseBaseObject = new HashSet<BusinessObject>();
            Pages = new HashSet<Page>();
            Permissions = new HashSet<Permission>();
        }

        public Guid Id { get; set; }
        public bool IsDeletedByUser { get; set; }
        public Guid? BaseObjectId { get; set; }
        public Guid? NamePropertyId { get; set; }
        public bool IsHierarchicalType { get; set; }
        public string QuickSearchAbbreviation { get; set; }
        public string Database { get; set; }
        public Guid? BusinessObjectGroupId { get; set; }
        public Guid BusinessModuleId { get; set; }
        public bool IsManyToManyConnectingObject { get; set; }
        public bool IsImported { get; set; }
        public bool IsCompiled { get; set; }
        public bool IsDeleted { get; set; }
        public string DisplayName { get; set; }
        public string PhysicalName { get; set; }

        public virtual BusinessObject BaseObject { get; set; }
        public virtual BusinessModule BusinessModule { get; set; }
        public virtual BusinessObjectGroup BusinessObjectGroup { get; set; }
        public virtual BusinessProperty NameProperty { get; set; }
        public virtual ICollection<BusinessObjectExpression> BusinessObjectExpressions { get; set; }
        public virtual ICollection<BusinessObjectRelation> BusinessObjectRelationFromObjects { get; set; }
        public virtual ICollection<BusinessObjectRelation> BusinessObjectRelationManyToManyObjects { get; set; }
        public virtual ICollection<BusinessObjectRelation> BusinessObjectRelationToObjects { get; set; }
        public virtual ICollection<BusinessProperty> BusinessProperties { get; set; }
        public virtual ICollection<ExpressionNode> ExpressionNodeCountObjects { get; set; }
        public virtual ICollection<ExpressionNode> ExpressionNodeFroms { get; set; }
        public virtual ICollection<ExpressionNode> ExpressionNodeTargetObjects { get; set; }
        public virtual ICollection<BusinessObject> InverseBaseObject { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}