// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class BusinessObjectGroup
    {
        public BusinessObjectGroup()
        {
            BusinessObjects = new HashSet<BusinessObject>();
        }

        public Guid Id { get; set; }
        public string GroupName { get; set; }
        public bool IsMenuGroup { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<BusinessObject> BusinessObjects { get; set; }
    }
}