// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class BusinessObjectRelation
    {
        public BusinessObjectRelation()
        {
            ForeignKeys = new HashSet<ForeignKey>();
            MetadataItemPathRelations = new HashSet<MetadataItemPathRelation>();
        }

        public Guid Id { get; set; }
        public string RelationName { get; set; }
        public bool IsBaseObjectRelation { get; set; }
        public Guid? ManyToManyObjectId { get; set; }
        public Guid FromObjectId { get; set; }
        public Guid ToObjectId { get; set; }
        public int FromEnd { get; set; }
        public int ToEnd { get; set; }
        public string FromRelationName { get; set; }
        public string ToRelationName { get; set; }
        public int? DeleteBehavior { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BusinessObject FromObject { get; set; }
        public virtual BusinessObject ManyToManyObject { get; set; }
        public virtual BusinessObject ToObject { get; set; }
        public virtual ICollection<ForeignKey> ForeignKeys { get; set; }
        public virtual ICollection<MetadataItemPathRelation> MetadataItemPathRelations { get; set; }
    }
}