// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class DatabaseInfo
    {
        public DatabaseInfo()
        {
            BusinessModules = new HashSet<BusinessModule>();
        }

        public Guid Id { get; set; }
        public string MachineName { get; set; }
        public string MachineAddress { get; set; }
        public string DatabaseServerInstanceName { get; set; }
        public string DatabaseName { get; set; }
        public bool IntegratedSecurity { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public int ServerType { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<BusinessModule> BusinessModules { get; set; }
    }
}