// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class DatabaseDataType
    {
        public DatabaseDataType()
        {
            ImportPropertyInfos = new HashSet<ImportPropertyInfo>();
        }

        public Guid Id { get; set; }
        public int ServerType { get; set; }
        public string DbDataType { get; set; }
        public int DbTypeEnumValue { get; set; }
        public int? NumericPrecision { get; set; }
        public int? NumericScale { get; set; }
        public long? MaxCharactedLength { get; set; }
        public bool IsRequired { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<ImportPropertyInfo> ImportPropertyInfos { get; set; }
    }
}