// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class EnumerationValue
    {
        public EnumerationValue()
        {
            ExpressionNodes = new HashSet<ExpressionNode>();
        }

        public Guid Id { get; set; }
        public Guid EnumerationTypeId { get; set; }
        public string Value { get; set; }
        public string Abbreviation { get; set; }
        public bool IsDeleted { get; set; }

        public virtual EnumerationType EnumerationType { get; set; }
        public virtual ICollection<ExpressionNode> ExpressionNodes { get; set; }
    }
}