// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class EnumerationType
    {
        public EnumerationType()
        {
            BusinessProperties = new HashSet<BusinessProperty>();
            EnumerationValues = new HashSet<EnumerationValue>();
            ExpressionNodes = new HashSet<ExpressionNode>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool CanUserModify { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<BusinessProperty> BusinessProperties { get; set; }
        public virtual ICollection<EnumerationValue> EnumerationValues { get; set; }
        public virtual ICollection<ExpressionNode> ExpressionNodes { get; set; }
    }
}