// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class ImportPropertyInfo
    {
        public Guid Id { get; set; }
        public Guid ConvertedPropertyId { get; set; }
        public string OriginalImportName { get; set; }
        public Guid? OriginalPropertyTypeId { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BusinessProperty ConvertedProperty { get; set; }
        public virtual DatabaseDataType OriginalPropertyType { get; set; }
    }
}