// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class MetadataItemPathRelation
    {
        public Guid Id { get; set; }
        public int Index { get; set; }
        public Guid PathNodeId { get; set; }
        public Guid RelationId { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ExpressionNode PathNode { get; set; }
        public virtual BusinessObjectRelation Relation { get; set; }
    }
}