// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class Page
    {
        public Page()
        {
            Permissions = new HashSet<Permission>();
        }

        public Guid Id { get; set; }
        public int TemplateId { get; set; }
        public Guid PageObjectId { get; set; }
        public Guid? QueryId { get; set; }
        public Guid? FilterId { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BusinessObjectExpression Filter { get; set; }
        public virtual BusinessObject PageObject { get; set; }
        public virtual BusinessObjectExpression Query { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}