// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class Permission
    {
        public Guid Id { get; set; }
        public Guid RoleId { get; set; }
        public string Discriminator { get; set; }
        public Guid? FilterExpressionId { get; set; }
        public int? DeniedAccess { get; set; }
        public Guid? ModuleId { get; set; }
        public Guid? ObjectId { get; set; }
        public Guid? PageId { get; set; }
        public Guid? PropertyId { get; set; }
        public int? GrantedAccess { get; set; }
        public bool IsDeleted { get; set; }

        public virtual BusinessObjectExpression FilterExpression { get; set; }
        public virtual BusinessModule Module { get; set; }
        public virtual BusinessObject Object { get; set; }
        public virtual Page Page { get; set; }
        public virtual BusinessProperty Property { get; set; }
        public virtual Role Role { get; set; }
    }
}