// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DynamicContextConsoleClient.Models
{
    public partial class User
    {
        public User()
        {
            Groups = new HashSet<UsersGroup>();
            Roles = new HashSet<Role>();
        }

        public Guid Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public Guid? ContainerId { get; set; }
        public bool IsDeleted { get; set; }

        public virtual Container Container { get; set; }

        public virtual ICollection<UsersGroup> Groups { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}